audit_header: false
title: DMV Real Estate Journal
description: Kristy Moore, a top Real Estate Agent in the DC Metro Area, shares his own internal agent training for free. His Real Estate Coaching, Tips and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: https://www.eventbrite.com/e/lxr-coaching-agent-business-planning-clinic-tickets-47192108868
  - title: Strategy Call
    url: /strategy-call/
  - title: Subscribe
    url: /subscribe/
  - title: Sponsorship Partners
    url: /partners/

emma:
  lightbox:
  form:

client:
  name: Kristy Moore
  title:
  license_number:
  about_markdown: |
    Local Expert Realty is a top producing real estate team in the metro DC area run by Broker and Founder, Kristy Moore. Prior to founding this innovative company she founded Moore Realty Services and grew it to a top producing real estate team in the metro DC area winning an award in 2015 for the Best Teams in America. Local Expert Realty’s philosophy is that ‘Performance Beats Promises’. Our statistics consistently outperform other agents in our marketplace. We get our sellers more money and our buyers better deals than any other team in the area. Our team of Realtors, marketing and lead specialists, contract administrators, and closing coordinators ensures every client receives top notch service every time. Call us today to find out how you can “Experience the Difference”.
  market: DC Metro Area
  brand: Local Expert Realty
  brokerage:
  address: 705 Park Ave, Falls Church, VA 22046
  phone: 888-297-8393
  phone_type:
  phone2:
  phone2_type:
  email: Kristy@LocalExpertRealty.com
  url: http://LocalExpertRealty.com

CTAs:
  # first_CTA_text: Join Our Team
  # first_CTA_URL: /join-our-team/
  # second_CTA_text: Home Search
  # second_CTA_URL: http://www.valleyoregonhomes.com/search/advanced_search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.valleyoregonhomes.com/cma/property-valuation/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.valleyoregonhomes.com/search/advanced_search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/LXR-Real-Estate-Coaching-1609495752460464/
  linkedin_url: https://www.linkedin.com/in/kristylynam/
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Careers and Training Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: Boost your Career with Veteran Real Estate Agent Jason Cadwell
  description: A Podcast about -- MARKET -- Real Estate; It's industry, and the people working in it. Whether you're just starting out, aspiring to begin, or been working in the field for a few years, tune in to get updates, tips, tricks and more!
  keywords: Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer

  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: LXR Real Estate Coaching
  hero_background_hex: '#f26532'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#1c3f95'
  theme_color: '#f26532'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  # shadow_color: rgb(238, 238, 238)

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
